spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbo
    username: root
    password: 123456789ohidul*#
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true